services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse_proxy
    depends_on:
      - frontend

  frontend:
    image: todo-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173